apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file dev/docker-compose-dev.yml convert -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  type: LoadBalancer
  ports:
    - name: "8890"
      port: 8890
      targetPort: 8890
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
