apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file dev/docker-compose-dev.yml convert -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "5342"
      port: 5342
      targetPort: 5432
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
