---
version: "3.9"
services:
  app:
    container_name: app
    build: ..
    ports:
      - 8890:8890
    tty: true
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/user_db
  db:
    container_name: app
    image: postgres
    restart: always
    ports:
      - 5342:5432
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: user_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "user_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
